export const RETRIEVE_ALL_CHURRAS = "RETRIEVE_ALL_CHURRAS";
export const CREATE_CHURRAS = "CREATE_CHURRAS";
export const ADD_PARTICIPANTE = "ADD_PARTICIPANTE";
export const UPDATE_CHURRAS = "UPDATE_CHURRAS";